-- MySQL Script generated by MySQL Workbench
-- seg 25 abr 2022 10:26:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DevJobs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DevJobs` ;

-- -----------------------------------------------------
-- Schema DevJobs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DevJobs` ;
USE `DevJobs` ;

-- -----------------------------------------------------
-- Table `DevJobs`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DevJobs`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `DevJobs`.`Usuario` (
  `cpf` CHAR(11) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `funcionarioOrContratante` CHAR(1) NOT NULL DEFAULT 'U',
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DevJobs`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DevJobs`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `DevJobs`.`Funcionario` (
  `cpfFuncionario` CHAR(11) NOT NULL,
  PRIMARY KEY (`cpfFuncionario`),
  CONSTRAINT `fk_cpfFuncionario1`
    FOREIGN KEY (`cpfFuncionario`)
    REFERENCES `DevJobs`.`Usuario` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DevJobs`.`Contratante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DevJobs`.`Contratante` ;

CREATE TABLE IF NOT EXISTS `DevJobs`.`Contratante` (
  `cpfContratante` CHAR(11) NOT NULL,
  `nomeEmpresa` VARCHAR(45) NOT NULL,
  `CNPJ` CHAR(14) NOT NULL,
  `dataAberturaEmpresa` DATE NOT NULL,
  PRIMARY KEY (`cpfContratante`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC),
  CONSTRAINT `fk_cpfContratante1`
    FOREIGN KEY (`cpfContratante`)
    REFERENCES `DevJobs`.`Usuario` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DevJobs`.`Curriculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DevJobs`.`Curriculo` ;

CREATE TABLE IF NOT EXISTS `DevJobs`.`Curriculo` (
  `cidadeOrigem` VARCHAR(50) NOT NULL,
  `estadoOrigem` CHAR(2) NOT NULL,
  `github` VARCHAR(45) NOT NULL,
  `linkedIn` VARCHAR(45) NULL,
  `objetivo` VARCHAR(200) NOT NULL,
  `formacaoAcademica` VARCHAR(150) NOT NULL,
  `expProfissionaisRelevantes` VARCHAR(300) NOT NULL,
  `especialidade` VARCHAR(30) NOT NULL,
  `cpfFuncionario` CHAR(11) NOT NULL,
  `curriculoNome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`curriculoNome`),
  INDEX `fk_cpfFuncionario2_idx` (`cpfFuncionario` ASC) ,
  CONSTRAINT `fk_cpfFuncionario2`
    FOREIGN KEY (`cpfFuncionario`)
    REFERENCES `DevJobs`.`Funcionario` (`cpfFuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DevJobs`.`Jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DevJobs`.`Jobs` ;

CREATE TABLE IF NOT EXISTS `DevJobs`.`Jobs` (
  `descricao` VARCHAR(300) NOT NULL,
  `requisitos` VARCHAR(200) NOT NULL,
  `beneficios` VARCHAR(200) NOT NULL,
  `salario` DECIMAL(8,2) NULL,
  `remoto` VARCHAR(7) NOT NULL,
  `qtdVagas` INT NOT NULL,
  `cpfContratante` CHAR(11) NOT NULL,
  `jobNome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`jobNome`),
  INDEX `fk_cpfContratante2_idx` (`cpfContratante` ASC) ,
  CONSTRAINT `fk_cpfContratante2`
    FOREIGN KEY (`cpfContratante`)
    REFERENCES `DevJobs`.`Contratante` (`cpfContratante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DevJobs`.`Aplicacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DevJobs`.`Aplicacao` ;

CREATE TABLE IF NOT EXISTS `DevJobs`.`Aplicacao` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `motivo` VARCHAR(50) NOT NULL,
  `situacao` VARCHAR(8) NOT NULL,
  `curriculoNome` VARCHAR(50) NOT NULL,
  `jobNome` VARCHAR(50) NOT NULL,
  `cpfFuncionario` CHAR(11) NOT NULL,
  `cpfContratante` CHAR(11) NOT NULL,
  `aplicacaoNome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`aplicacaoNome`),
  INDEX `fk_cpfFuncionario3_idx` (`cpfFuncionario` ASC) ,
  INDEX `fk_cpfContratante3_idx` (`cpfContratante` ASC) ,
  INDEX `fk_curriculoNome_idx` (`curriculoNome` ASC) ,
  INDEX `fk_jobNome_idx` (`jobNome` ASC) ,
  CONSTRAINT `fk_curriculoNome`
    FOREIGN KEY (`curriculoNome`)
    REFERENCES `DevJobs`.`Curriculo` (`curriculoNome`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_jobNome`
    FOREIGN KEY (`jobNome`)
    REFERENCES `DevJobs`.`Jobs` (`jobNome`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cpfFuncionario3`
    FOREIGN KEY (`cpfFuncionario`)
    REFERENCES `DevJobs`.`Funcionario` (`cpfFuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cpfContratante3`
    FOREIGN KEY (`cpfContratante`)
    REFERENCES `DevJobs`.`Contratante` (`cpfContratante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
